version: "3"
services:
  chad:
    build:
      context: .
      args:
        NODE_ENV: production
    depends_on:
      - vosk
  vosk:
    image:
      "alphacep/kaldi-en:latest"
    ports:
      - "2700"